import { ProjectCard } from "@/components/projects/project-card";
import { Hero } from "@/components/sections-hero";
import { Button } from "@/components/ui/button";
import { Section } from "@/components/ui/section";
import { profile } from "@/data/profile";
import { pageMetadata } from "@/lib/metadata";
import { getProjects } from "@/lib/projects";

export const metadata = pageMetadata("AI Product Engineer", profile.summary, "/");

export default function Home() {
  const featuredProjects = getProjects().filter((project) => project.featured).slice(0, 3);
  return <><Hero /><Section><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Selected systems</p><h2 className="display-heading mt-4">Systems that earn trust through engineering discipline.</h2></div><Button href="/projects" secondary>All projects</Button></div><div className="grid gap-5 lg:grid-cols-3">{featuredProjects.map((project, index) => <ProjectCard key={project.slug} project={project} featured={index === 0} />)}</div></Section><Section className="border-y border-white/[0.07] bg-white/[0.015]"><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><p className="eyebrow">Engineering philosophy</p><div><h2 className="display-heading">Deterministic first. AI second.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">AI accelerates the build, but state, calculations, and irreversible decisions need clear boundaries. The work is designed around validation, operational context, and accountable human judgement.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/engineering-approach" secondary>Engineering approach</Button></div></div></div></Section><Section><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><p className="eyebrow">Operational foundation</p><div><h2 className="display-heading">Industrial engineering informs the systems, not just the software.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">A grounding in process, constraints, and operational improvement keeps AI product work connected to how decisions and workflows operate in practice.</p></div></div></Section><Section className="border-t border-white/[0.07] bg-white/[0.015]"><div className="max-w-3xl"><p className="eyebrow">Start a conversation</p><h2 className="display-heading mt-4">Explore the work or discuss the next systems challenge.</h2><p className="mt-6 text-lg leading-8 text-slate-400">Review the case studies, read the engineering approach, or get in touch about a role, product, or operational problem.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/projects">Review case studies</Button><Button href="/contact" secondary>Contact Glenn</Button></div></div></Section></>;
}