import Link from "next/link";
import { Section } from "@/components/ui/section";
import { additionalSystems, deterministicPrinciples, flagshipNotes, flagshipSlugs, methodologies } from "@/data/ai-systems-and-methods";
import { pageMetadata } from "@/lib/metadata";
import { getProjects } from "@/lib/projects";

export const dynamic = "force-static";
export const metadata = pageMetadata("AI Systems & Engineering Methods", "How Glenn Murray applies deterministic-first AI engineering across systems, delivery methods, prototypes, and research.", "/ai-systems-and-methods");

export default function AiSystemsAndMethodsPage() {
  const projects = new Map(getProjects().map((project) => [project.slug, project]));
  const flagship = flagshipSlugs.flatMap((slug) => {
    const project = projects.get(slug);
    return project ? [project] : [];
  });

  return <>
    <Section className="border-b border-white/[0.07] bg-white/[0.015]"><div className="max-w-4xl"><p className="eyebrow">AI Systems &amp; Engineering Methods</p><h1 className="page-heading mt-4">Deterministic-first AI engineering for systems that need to earn trust.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-400">Decidable logic stays deterministic. AI is used for constrained narration, interpretation, and pattern recognition over verified signals, with governed workflows and human review where impact or uncertainty is high.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/projects" className="text-sm font-semibold text-blue-400 hover:text-blue-300">View projects -&gt;</Link><Link href="/engineering-approach" className="text-sm font-semibold text-blue-400 hover:text-blue-300">Engineering approach -&gt;</Link></div></div></Section>
    <Section><div className="grid gap-10 lg:grid-cols-[220px_minmax(0,1fr)]"><p className="eyebrow">Core philosophy</p><div><h2 className="display-heading">Deterministic first, AI second.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{deterministicPrinciples.map((item) => <p key={item} className="surface-subtle rounded-xl p-5 text-sm leading-6 text-slate-300">{item}</p>)}</div></div></div></Section>
    <Section className="border-y border-white/[0.07] bg-white/[0.015]"><div className="max-w-4xl"><p className="eyebrow">Build methodology</p><h2 className="display-heading mt-4">Methods that keep AI-assisted delivery accountable.</h2><div className="mt-10 grid gap-5">{methodologies.map((method) => <article key={method.title} className="surface rounded-2xl p-6 md:p-8"><h3 className="text-2xl font-semibold tracking-tight text-white">{method.title}</h3><p className="mt-4 max-w-3xl text-base leading-7 text-slate-400">{method.summary}</p><ul className="mt-6 grid gap-2 sm:grid-cols-2">{method.points.map((point) => <li key={point} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-blue-400" aria-hidden="true" />{point}</li>)}</ul>{method.href && <Link href={method.href} className="mt-7 inline-flex text-sm font-semibold text-blue-400 hover:text-blue-300">{method.linkLabel} -&gt;</Link>}</article>)}</div></div></Section>
    <Section><div><p className="eyebrow">Flagship systems</p><h2 className="display-heading mt-4">The same principles, applied to different operational contexts.</h2><div className="mt-10 grid gap-5 lg:grid-cols-2">{flagship.map((project) => <article key={project.slug} className="surface rounded-2xl p-6 md:p-8"><p className="technical-label">{project.positioning}</p><h3 className="mt-3 text-2xl font-semibold tracking-tight text-white">{project.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{project.summary}</p><div className="mt-5 flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">{item}</span>)}</div><ul className="mt-6 space-y-2">{flagshipNotes[project.slug as keyof typeof flagshipNotes].map((note) => <li key={note} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-blue-400" aria-hidden="true" />{note}</li>)}</ul><Link href={`/projects/${project.slug}`} className="mt-7 inline-flex text-sm font-semibold text-blue-400 hover:text-blue-300">View case study -&gt;</Link></article>)}</div></div></Section>
    <Section className="border-y border-white/[0.07] bg-white/[0.015]"><div><p className="eyebrow">Additional systems and research</p><h2 className="display-heading mt-4">Explorations presented with their maturity intact.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">These items are prototypes, concepts, experimental implementations, or research frameworks. They are not represented as equivalent production case studies.</p><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{additionalSystems.map((system) => <article key={system.title} className="surface-subtle rounded-xl p-5"><span className="inline-flex rounded-full border border-white/10 px-3 py-1 text-xs font-semibold text-slate-300">{system.maturity}</span><h3 className="mt-4 text-lg font-semibold tracking-tight text-white">{system.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{system.summary}</p><ul className="mt-4 space-y-2">{system.details.map((detail) => <li key={detail} className="text-sm leading-6 text-slate-300">{detail}</li>)}</ul></article>)}</div></div></Section>
    <Section><div className="grid gap-10 lg:grid-cols-[220px_minmax(0,1fr)]"><p className="eyebrow">Common throughline</p><div><h2 className="display-heading">The methodology is part of the deliverable.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">Across finance, industrial operations, compliance, advertising, software delivery, and security research, deterministic layers handle everything decidable and AI remains narrowly scoped. Tests and acceptance criteria define correctness; traceability, observability, and human review govern uncertain operations.</p><p className="mt-5 max-w-3xl text-base leading-8 text-slate-400">See the <Link href="/engineering-approach" className="text-blue-400 hover:text-blue-300">Engineering Approach</Link> for the delivery practices behind these systems.</p></div></div></Section>
  </>;
}